### ISSUE TITLE
Scale and Robustness on Thyra Frontend

### ISSUE THREAD

**Issue by 0xMazout** [massalabs/thyra#556]
Context
We are going to make a rebrand on Thyra , at this opportunity we should add more Robustness
We should take decision to prepare scaling too 
There is a list of "Nice To Have" we have enumerate 

- [ ] Separate Frontend from Thyra into another project to avoid CI problems 
- [ ] Add Internationalisation
- [ ] Generic styles with Twin Macro
- [ ] Fusion of Plugin Manager Page Project and HomePage Project into one Project
- [ ] Fusion of HomePage and Plugin manager Page in one Page ?
- [ ] Create a CI for the frontend only 
- [ ] Create End to End Test
- [ ] Implement React Query (Needed to learn on it before)
- [ ] Creation of StoryBook ( Framework of UI) Optionnal
- [ ] Using Consts and Shared Styles

This issue is a Meta Issue created to create an arbitrage on this and Create issues related to each big subjects

How to
Arbitrage on the needs , creation of issues related to validated needs

**Comment by SlnPons** [comment]
@0xMazout are you ok to close this issue now you've worked with @mazmassa on setting up the basics?

**Comment by 0xMazout** [comment]
Yes clearly
